@startuml

actor Admin
boundary AccountManageView
control AccountControl
entity Account

Admin -> AccountManageView: 1. Click "Create Account" button
AccountManageView -> AccountControl: 2. Request to create a new account
AccountControl -> Account: 3. Generate new account details
AccountControl -> AccountControl: 4. Validate account information
alt Valid Information
    AccountControl -> Account: 5. Create new account
    AccountControl -> AccountManageView: 6. Notify account creation success
else Invalid Information
    AccountControl -> AccountManageView: 6. Notify account creation failure
    AccountControl -> AccountManageView: 7. Display error message
end

@enduml
