@startuml
actor Customer 
boundary SearchProductView 
control SearchProductControl

activate SearchProductView
Customer -> SearchProductView: Click on search button
Customer -> SearchProductView: Click on filter options

SearchProductView -> SearchProductControl: Filter item
activate SearchProductControl

alt Item found
    SearchProductControl --> SearchProductView: Return item product
    SearchProductView -> SearchProductView: Display item
else Item not found
    SearchProductControl --> SearchProductView: Return message
    SearchProductView -> SearchProductView: Display message
end

deactivate SearchProductView

@enduml