@startuml

actor ShopOwner 
boundary StaffManageView 
boundary StaffDetailsView 
control StaffControl
entity DB 

ShopOwner -> StaffManageView: Open Staff Management View
activate StaffManageView 
StaffManageView -> StaffControl : Get list of Staffs
activate StaffControl 
StaffControl -> DB: Get list of Staffs
deactivate StaffControl
activate DB
DB --> StaffManageView: Return list of Staffs
deactivate DB
StaffManageView -> StaffManageView: Display list of Staffs
activate StaffManageView 
deactivate StaffManageView 

opt InsertNewStaff
    ShopOwner -> StaffManageView: Click on "Add staff" button
    StaffManageView -> StaffManageView: Display form to enter staff info
    activate StaffManageView
    ShopOwner -> StaffManageView : Enter form
    StaffManageView -> StaffControl: Request to add new staff
    activate StaffControl    
    deactivate StaffManageView
    StaffControl -> StaffControl: Validate input
    activate StaffControl
    StaffControl -> DB: Create new staff information
    activate DB
    deactivate StaffControl
    DB--> StaffControl : Notify success/failure
    deactivate DB
    StaffControl --> StaffManageView: Notify success/failure
    deactivate StaffControl
end   

opt UpdateStaff
    ShopOwner -> StaffManageView: Select staff info to update
    StaffManageView -> StaffManageView: Display form to enter info
    activate StaffManageView
    ShopOwner-> StaffManageView : Enter form
    StaffManageView -> StaffControl: Request to update new staff info
    activate StaffControl    
    deactivate StaffManageView
    StaffControl -> StaffControl: Validate input
    activate StaffControl
    StaffControl -> DB: Update staff info
    activate DB
    deactivate StaffControl
    DB--> StaffControl : Notify success/failure
    deactivate DB
    StaffControl --> StaffManageView: Notify success/failure
    deactivate StaffControl
end  

opt DeleteStaff
    ShopOwner -> StaffManageView: Select staff info to delete
    StaffManageView -> StaffManageView: Display confirm dialog
    activate StaffManageView
    ShopOwner -> StaffManageView: Confirm delete
    
    StaffManageView -> StaffControl: Request to delete staff info
    deactivate StaffManageView
    activate StaffControl    

    StaffControl -> DB: Delete staff info
    deactivate StaffControl
    activate DB
    DB--> StaffControl : Notify success/failure
    deactivate DB
    activate StaffControl
    StaffControl --> StaffManageView: Notify success/failure
    deactivate StaffControl
end  

opt SearchStaff
    ShopOwner -> StaffManageView: Choose Search Action
    StaffManageView -> StaffManageView: Display search interface
    activate StaffManageView 
    ShopOwner -> StaffManageView: Enter search criteria
    StaffManageView -> StaffControl: Request to search staff info
    activate StaffControl
    StaffControl -> StaffControl: Validate search criteria
    StaffControl -> StaffControl: Search staff info
    StaffControl --> StaffManageView: Return search results
    deactivate StaffControl
    StaffManageView -> StaffManageView: Display search results
    deactivate StaffManageView 
end  


@enduml