@startuml

actor Admin
boundary RevenueStatisticsView
control RevenueStatisticsControl
entity DB

Admin -> RevenueStatisticsView: Open "Revenue Statistics" page
activate RevenueStatisticsView
Admin -> RevenueStatisticsView: Choose type of report want to display
RevenueStatisticsView -> RevenueStatisticsControl: Request revenue statistics data
activate RevenueStatisticsControl
RevenueStatisticsView -> RevenueStatisticsView: Display loading


RevenueStatisticsControl -> DB: Retrieve data
activate DB
deactivate RevenueStatisticsControl

DB --> RevenueStatisticsControl: Return data
activate RevenueStatisticsControl
deactivate DB

RevenueStatisticsControl -> RevenueStatisticsControl: Process revenue statistics
RevenueStatisticsControl -> RevenueStatisticsView: Return processed statistics
deactivate RevenueStatisticsControl

RevenueStatisticsView -> RevenueStatisticsView: Display revenue statistics

@enduml
