@startuml

actor Customer 
boundary SignUpView 
control SignUpControl
entity DB

activate SignUpView
Customer -> SignUpView: Click "Sign Up" button

SignUpView -> SignUpView: Display form to enter account details
activate SignUpView
Customer-> SignUpView : Enter customer's information included username and password
SignUpView -> SignUpControl: Request to insert new account
activate SignUpControl    
deactivate SignUpView
SignUpControl -> SignUpControl: Check validate input
activate SignUpControl

alt Invalid Input
    SignUpControl --> SignUpView : Send error message
    SignUpView -> SignUpView : Display error notification
    activate SignUpView
    deactivate SignUpView
else Valid Input
    SignUpView -> SignUpControl: Send username and password
    SignUpControl -> DB: Send username and password
    activate DB
    DB -> DB: Check validate information
    activate DB
    deactivate DB

    alt Invalid Information
        DB --> SignUpControl: Send error message
        SignUpControl --> SignUpView: Display error notification

    else Valid Information
        DB --> SignUpControl: Send successful message
        SignUpControl --> SignUpView: Successful notification
    end
end
@enduml