@startuml
actor Admin 
boundary AccountManageView 
boundary UserAccountView
control AccountControl
entity DB 

Admin -> AccountManageView: Open Account Management View
activate AccountManageView 
AccountManageView -> AccountControl: Get list of Accounts
activate AccountControl 
AccountControl -> DB: Get list of Accounts
deactivate AccountControl
activate DB
DB --> AccountManageView: Return list of Accounts
deactivate DB
AccountManageView -> AccountManageView: Display list of Accounts
activate AccountManageView 
deactivate AccountManageView 

Admin -> AccountManageView: Click on an account

AccountManageView -> AccountControl: Get info account details
activate AccountControl
AccountControl -> DB: Get info account details
deactivate AccountControl
activate DB

DB --> AccountControl: Return account info
deactivate DB
activate AccountControl

AccountControl --> AccountManageView: Return account info
deactivate AccountControl

AccountManageView -> AccountManageView: Display Account details
Admin -> AccountManageView: Click on "Send notice"
AccountManageView -> AccountManageView: Display input form
activate AccountManageView

Admin -> AccountManageView: Enter form
AccountManageView -> AccountControl: Send message to Control
activate AccountControl
AccountControl -> DB: Send notice
deactivate AccountControl
activate DB
DB --> AccountControl: Successful message
deactivate DB
activate AccountControl
AccountControl --> AccountManageView: Successful message
AccountControl --> UserAccountView: Notify to user account
deactivate AccountControl

deactivate AccountManageView

@enduml