@startuml
|Admin|
start
:Click on an account;
|System|
:Load account details;
|Admin|
:Click "Delete account";
|System|
if (Confirm?) then (Yes)
:Delete account;
:Send message to user email;
else (No)
endif
stop
@enduml