@startuml
|ShopOwner|
start
:Click on an staff information;
:Click on "Update salary" button;
|System|
:Load input form;
|ShopOwner|
:Enter value;
|System|
if (Validate) then (Valid)
:Update salary;
else (Not valid)
:Show error message;
endif
stop
@enduml